# Generated by Django 4.2 on 2026-05-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='defaultpass', max_length=255),
        ),
    ]
