# Generated by Django 4.2 on 2026-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_budgetallocation_remove_department_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
